services:
  api:
    build: ./Api
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=Stock;User Id=sa;Password=xirmus-nEtwe6-joxhaq;TrustServerCertificate=True;Encrypt=False;

  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure-sql-edge
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=xirmus-nEtwe6-joxhaq
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
      - metabase-data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
      JAVA_OPTS: -Xmx1g
    depends_on:
      - db
    restart: unless-stopped

volumes:
  sql_data:
  metabase-data: