// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250904092702_AddWeightedIndexAndOtcIndex")]
    partial class AddWeightedIndexAndOtcIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DealerSelf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Dji")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeignInvestor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentTrust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarginBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nasdaq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sox")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sp500")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taiex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaiexVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tpex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TpexVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsGovernmentBound")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsdExchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Vix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
